from bluetti_modbus_lib.devices.ac500 import AC500


def test_no_block_spans_an_address_ac500_gives_no_evidence_for():
    # Real hardware regression: bluetti-community/bluetti-modbus-tcp-slave#5
    # (comment https://github.com/bluetti-official/bluetti-modbus-tcp-slave/
    # issues/5#issuecomment-5538143820) showed bluetti-modread timing out on
    # read_holding_registers(50002, 11) - BluettiDevice's default max_gap=5
    # block-batching merged ac_o_p_total/pv_i_p_total/g_i_p_total/
    # d_inverter_total/ac_o_e_total (50002, 50004, 50006, 50008, 50012) into
    # one combined read that also swept in 50010 (pv_ac_p's Balco260
    # address, confirmed "Illegal Data Address" on AC500 per bluetti-
    # registers#13) - the whole block then fails even though every declared
    # field is fine read on its own. AC500's register_ranges (see
    # devices/ac500.py, generated by import.py from the real field
    # addresses/counts) should keep every block to exactly one field, so no
    # block can ever bridge across an address this device has no evidence
    # for.
    device = AC500(None)

    plan = device._build_plan()

    assert plan.blocks.keys() == {"holding"}
    blocks = plan.blocks["holding"]
    for start, count in blocks:
        end = start + count - 1
        assert not (start <= 50010 <= end), (
            f"block ({start}, {count}) spans the confirmed-bad address 50010"
        )
    # The specific failure from the traceback: no single block covers both
    # ac_o_p_total (50002) and ac_o_e_total (50012) any more.
    assert not any(
        start <= 50002 and start + count - 1 >= 50012 for start, count in blocks
    )


def test_every_field_is_its_own_read_block():
    # Stronger than the above: with no confirmed-good gaps between any two
    # AC500 fields yet, every block should be exactly one field wide -
    # proves register_ranges isn't just narrowly avoiding 50010, it avoids
    # bridging over *any* unconfirmed address.
    device = AC500(None)

    plan = device._build_plan()

    field_count = len(list(device.field_names()))
    block_count = len(plan.blocks["holding"])
    # pv_dc_count/pv_ac_count share one address (50267), so they collapse
    # into a single block - everything else is 1:1.
    assert block_count == field_count - 1
